title: Data Science and AI Course
description: A comprehensive curriculum covering data fundamentals, data wrangling, visualization, statistical analysis, and machine learning fundamentals
baseurl: "/tamkeen-data"
url: "https://codebyshennan.github.io"

# Repository information
repository: codebyshennan/tamkeen-data
github:
  repository_url: https://github.com/codebyshennan/tamkeen-data

# Build settings
markdown: kramdown
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-remote-theme

# Error handling
liquid:
  error_mode: warn
  strict_variables: false
  strict_filters: false

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Default front matter
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

theme: jekyll-theme-primer

# Include directories
include:
  - .assets

# Exclude from processing
exclude:
  - .git/
  - .gitbook/
  - .gitignore
  - node_modules/
  - 0-prep/
  - 1-data-fundamentals/
  - docs/0-prep/
  - docs/1-data-fundamentals/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# GitHub Pages settings
