title: Data Science and AI Course
description: A comprehensive curriculum covering data fundamentals, data wrangling, visualization, statistical analysis, and machine learning fundamentals
baseurl: "/tamkeen-data"
url: "https://codebyshennan.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Default front matter
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Include directories
include:
  - _posts
  - _pages
  - _layouts
  - _includes
  - assets
  - 0-prep
  - 1-data-fundamentals
  - 2-data-wrangling
  - 3-data-visualization
  - 4-stat-analysis
  - 5-ml-fundamentals
  - 6-capstone
  - additional-resources

# Exclude from processing
exclude:
  - .git/
  - .gitbook/
  - .gitignore
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock

# GitHub Pages settings
remote_theme: pages-themes/primer@v0.6.0 
