source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-remote-theme", "~> 0.4.3"
gem "kramdown", "~> 2.3.1"
gem "liquid", "~> 4.0"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-github-metadata"
end 
