source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-theme-primer", "~> 0.6.0"
gem "minima", "~> 2.5"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-tabs", "~> 1.1.0"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-tabs", "~> 1.1.0"
end 
