name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "12"

      - name: Install GitBook
        run: |
          npm install -g gitbook-cli@2.3.2
          gitbook fetch 3.2.3
          gitbook install

      - name: Build GitBook
        run: |
          gitbook build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _book
          branch: gh-pages
